services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server_usuario
    ports: # not actually needed, because the two services are on the same network
      - "8002:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  web_api:
    image: klbraguilar/nurbnb-usuario
    container_name: web_api_usuario
    ports:
      - "8001:80"
    depends_on:
      - sql
